# Generated by Django 6.0 on 2026-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('citizen', 'Citizen'), ('responder', 'Responder')], default='citizen', max_length=20),
        ),
    ]
